# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setObjectName("lcd")
        self.verticalLayout.addWidget(self.lcd)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mul = QtWidgets.QPushButton(self.centralwidget)
        self.mul.setEnabled(True)
        self.mul.setMinimumSize(QtCore.QSize(60, 60))
        self.mul.setMaximumSize(QtCore.QSize(60, 60))
        self.mul.setObjectName("mul")
        self.gridLayout.addWidget(self.mul, 1, 3, 1, 1)
        self.equ = QtWidgets.QPushButton(self.centralwidget)
        self.equ.setEnabled(True)
        self.equ.setMinimumSize(QtCore.QSize(60, 60))
        self.equ.setMaximumSize(QtCore.QSize(60, 60))
        self.equ.setObjectName("equ")
        self.gridLayout.addWidget(self.equ, 3, 3, 1, 1)
        self.num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.num_6.setEnabled(True)
        self.num_6.setMinimumSize(QtCore.QSize(60, 60))
        self.num_6.setMaximumSize(QtCore.QSize(60, 60))
        self.num_6.setObjectName("num_6")
        self.gridLayout.addWidget(self.num_6, 1, 2, 1, 1)
        self.div = QtWidgets.QPushButton(self.centralwidget)
        self.div.setEnabled(True)
        self.div.setMinimumSize(QtCore.QSize(60, 60))
        self.div.setMaximumSize(QtCore.QSize(60, 60))
        self.div.setObjectName("div")
        self.gridLayout.addWidget(self.div, 2, 3, 1, 1)
        self.num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.num_4.setEnabled(True)
        self.num_4.setMinimumSize(QtCore.QSize(60, 60))
        self.num_4.setMaximumSize(QtCore.QSize(60, 60))
        self.num_4.setObjectName("num_4")
        self.gridLayout.addWidget(self.num_4, 1, 0, 1, 1)
        self.num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.num_1.setEnabled(True)
        self.num_1.setMinimumSize(QtCore.QSize(60, 60))
        self.num_1.setMaximumSize(QtCore.QSize(60, 60))
        self.num_1.setObjectName("num_1")
        self.gridLayout.addWidget(self.num_1, 0, 0, 1, 1)
        self.num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7.setEnabled(True)
        self.num_7.setMinimumSize(QtCore.QSize(60, 60))
        self.num_7.setMaximumSize(QtCore.QSize(60, 60))
        self.num_7.setObjectName("num_7")
        self.gridLayout.addWidget(self.num_7, 2, 0, 1, 1)
        self.num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.num_9.setEnabled(True)
        self.num_9.setMinimumSize(QtCore.QSize(60, 60))
        self.num_9.setMaximumSize(QtCore.QSize(60, 60))
        self.num_9.setObjectName("num_9")
        self.gridLayout.addWidget(self.num_9, 2, 2, 1, 1)
        self.num_2 = QtWidgets.QPushButton(self.centralwidget)
        self.num_2.setEnabled(True)
        self.num_2.setMinimumSize(QtCore.QSize(60, 60))
        self.num_2.setMaximumSize(QtCore.QSize(60, 60))
        self.num_2.setObjectName("num_2")
        self.gridLayout.addWidget(self.num_2, 0, 1, 1, 1)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setEnabled(True)
        self.add.setMinimumSize(QtCore.QSize(60, 60))
        self.add.setMaximumSize(QtCore.QSize(60, 60))
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 3, 0, 1, 1)
        self.num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.num_0.setEnabled(True)
        self.num_0.setMinimumSize(QtCore.QSize(60, 60))
        self.num_0.setMaximumSize(QtCore.QSize(60, 60))
        self.num_0.setObjectName("num_0")
        self.gridLayout.addWidget(self.num_0, 3, 1, 1, 1)
        self.sub = QtWidgets.QPushButton(self.centralwidget)
        self.sub.setEnabled(True)
        self.sub.setMinimumSize(QtCore.QSize(60, 60))
        self.sub.setMaximumSize(QtCore.QSize(60, 60))
        self.sub.setObjectName("sub")
        self.gridLayout.addWidget(self.sub, 3, 2, 1, 1)
        self.num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.num_5.setEnabled(True)
        self.num_5.setMinimumSize(QtCore.QSize(60, 60))
        self.num_5.setMaximumSize(QtCore.QSize(60, 60))
        self.num_5.setObjectName("num_5")
        self.gridLayout.addWidget(self.num_5, 1, 1, 1, 1)
        self.CE = QtWidgets.QPushButton(self.centralwidget)
        self.CE.setEnabled(True)
        self.CE.setMinimumSize(QtCore.QSize(60, 60))
        self.CE.setMaximumSize(QtCore.QSize(60, 60))
        self.CE.setObjectName("CE")
        self.gridLayout.addWidget(self.CE, 0, 3, 1, 1)
        self.num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.num_3.setEnabled(True)
        self.num_3.setMinimumSize(QtCore.QSize(60, 60))
        self.num_3.setMaximumSize(QtCore.QSize(60, 60))
        self.num_3.setObjectName("num_3")
        self.gridLayout.addWidget(self.num_3, 0, 2, 1, 1)
        self.num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.num_8.setEnabled(True)
        self.num_8.setMinimumSize(QtCore.QSize(60, 60))
        self.num_8.setMaximumSize(QtCore.QSize(60, 60))
        self.num_8.setObjectName("num_8")
        self.gridLayout.addWidget(self.num_8, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.num_0.raise_()
        self.lcd.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mul.setText(_translate("MainWindow", "*"))
        self.equ.setText(_translate("MainWindow", "="))
        self.num_6.setText(_translate("MainWindow", "6"))
        self.div.setText(_translate("MainWindow", "/"))
        self.num_4.setText(_translate("MainWindow", "4"))
        self.num_1.setText(_translate("MainWindow", "1"))
        self.num_7.setText(_translate("MainWindow", "7"))
        self.num_9.setText(_translate("MainWindow", "9"))
        self.num_2.setText(_translate("MainWindow", "2"))
        self.add.setText(_translate("MainWindow", "+"))
        self.num_0.setText(_translate("MainWindow", "0"))
        self.sub.setText(_translate("MainWindow", "-"))
        self.num_5.setText(_translate("MainWindow", "5"))
        self.CE.setText(_translate("MainWindow", "CE"))
        self.num_3.setText(_translate("MainWindow", "3"))
        self.num_8.setText(_translate("MainWindow", "8"))

